name: ny_times_api_test_flutter
description: New york articles.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Equatable
  equatable: ^2.0.5

  #Route Master
  routemaster: ^1.0.1

  #Reactive Forms
  reactive_forms: ^14.1.0

  #logger
  logger:

  #Get it
  get_it: ^7.2.0
  
  #dartz
  dartz: ^0.10.1

  #Mockito
  mockito: ^5.3.2

  #internet connection checker plus
  internet_connection_checker_plus: ^1.0.1

  #flutter secure storage
  flutter_secure_storage: ^6.0.0

  #http
  http: ^0.13.5

  #google fonts
  google_fonts: ^3.0.1

  #flutter bloc  
  flutter_bloc: ^8.1.1

  #url launcher
  url_launcher: ^6.1.6
  #flutter toast
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  stacked_generator:
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
